### PR TITLE
Support for ubuntu 20.04

### PR DESCRIPTION
**Pull request by Chithrak07**
Add Ubuntu 20.04 to the supported versions list.

### CODE REVIEW

**Comment by dale-c-anderson** [comment]
@Chithrak07 Has 20.04 actually been tested? All I can see in molecule is a test for 18.04.

**Comment by Chithrak07** [comment]
@dale-c-anderson : Please review.

**Comment by dale-c-anderson** [comment]
@Chithrak07 have molecule tests for 20.04 been run, and did they pass?

**Comment by Chithrak07** [comment]
@dale-c-anderson : Yes
ansible-role-php

ansible-role-php-verify

**Review by dale-c-anderson — COMMENTED** [review]
Reviewed

**Pull request merged**
